### ISSUE TITLE
/project/new hangs on staging server

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#125]
I tried to create a new project on the staging server:

https://stage.librecores.org/berndca/test

The process hangs and refresh just brings the same page back.

**Comment by eliaskousk** [comment]
This also happens on my local vm sometimes. I didn't give it much consideration since I can't reproduce it. I was thinking that it might have to do with the vm sleeping or shuting down when my host sleeps or shuts down and maybe the rabbitmq daemon doesn't like such interruptions. I've made this conclusion since on a clean vm (destroy and rebuild) this problem never happens.

Now that we see it happening on staging / production we should definitely investigate it. @imphil let me know if I can help you with it somehow. Maybe the rabbitmq logs can give us an explanation. I'll save my local dev ones when it happens again.

**Comment by imphil** [comment]
On the staging server, this most likely was a deployment issue. I took care to manually convert the production instance to the new database settings, but didn't do so for the staging one. I've now re-deployed staging and it should be fine now. However, the test project is gone as we always deploy our database fixtures on stage and delete anything else.
