### ISSUE TITLE
Verify user email addresses

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#142]
Verify email addresses given by users on registration and when changing the email address by sending them a link to click on.

Users can register and use the site without being verified, however, no mails should be sent to email addresses which are not verified (except for the verification mail itself, of course).

Dependency: https://github.com/librecores/librecores-web/issues/94

**Comment by eliaskousk** [comment]
Thanks for opening the issue, you were quicker. This feature should be much easier than the complete notification system (#143) and thus I will begin working on this. I will try to make it a bit abstract so that the actual generation of e-mails can be reused in #143.

**Comment by Agathver** [comment]
Isn't verification of user emails a standard part of FOSUserBundle ?

**Comment by eliaskousk** [comment]
Yes the FOS bundle supports verification of user emails during registration but we currently don't use it and haven't tested it on either dev or production. For the latter we will use an AWS email service that Philipp will setup soon (possibly in parallel).

Also changing email address requires some attention and we also have the option of not allowing it.

Last but not least, thank you for the html emails repo, this should be great for our purposes since I agree that we don't want to mess with handcrafting emails without some help by such template library.
