### ISSUE TITLE
Algolia: Added categories are not sent to index

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#254]
When I add a category to a project the changes are not reflected in the Algolia index.

STR:
- Choose any project without classifications.
- Navigate to the project's settings page.
- Add a category, click on "update project"
- Verify that the classification is visible on the project page.
- Click on the classification on the project page.

Expected outcome:
- Algolia finds the projects with this clasisficaton

Actual outcome:
- Algolia finds nothing

Further checking reveals that the classification is also not present in the index as shown in the Algolia web UI. Possibly no update is triggered?

**Comment by imphil** [comment]
Further information: Manually pushing the data to Algolia using "algolia:import" on the command line shows the information. So only the trigger seems to be missing.

**Comment by sandipbhuyan** [comment]
At the current state when someone is updating the project then it will be getting updated in algolia's dashboard. I am checking this issue. I think it is taking some time for getting updated in algolia.

**Comment by imphil** [comment]
> At the current state when someone is updating the project then it will be getting updated in algolia's dashboard.

It does when changing other fields in addition to the categories. When *only changing the categories* (as in the STR above) an index update is not triggered.

**Comment by sandipbhuyan** [comment]
Understood that is because classifications are from another entity. I am figuring out an appropriate solution for it.

**Comment by agathver** [comment]
@sandipbhuyan Encapsulate proper association management rules: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#association-management-methods

This is because in https://github.com/librecores/librecores-web/blob/master/site/src/Librecores/ProjectRepoBundle/Controller/ProjectController.php#L270, you set a project to the newly created project classification entity, while you are not updating the associated Project by using `addProjectClassification`.

Only syncing the changes is not enough, you need to update a database field, such as `dateLastModified` in `addProjectClassification` in order to make doctrine emit life-cycle hooks, which Algolia uses to sync the entities. A good choice is to set `dateLastUpdated` to `\DateTime('now')`

https://github.com/librecores/librecores-web/blob/master/site/src/Librecores/ProjectRepoBundle/Entity/Project.php#L1064

**Comment by sandipbhuyan** [comment]
Thanks @agathver Not this thing is resolved
