### ISSUE TITLE
As a developer I want to create a new LibreCores organization

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#7]
A LibreCores organization is, similar to GitHub organizations, a collection of projects. They can be maintained by a group of people (a team) and serve as a "namespace" for the contained projects.

Requirements:
- User management #8, #9 
- Create organization

**Comment by eliaskousk** [comment]
Just a note here that I'm working on this!

**Comment by imphil** [comment]
just assign the ticket to yourself and add it to the wip column in the "Projects" view.

**Comment by imphil** [comment]
@eliaskousk I pushed a PR with an updated routing scheme which better fits the organizations, find it here: https://github.com/librecores/librecores-web/pull/74

Please have a look. We especially should have a closer look at the join/remove/etc. actions and see which ones we can make part of the settings page. 

Elias, how far did you get with the revised organization member stuff? I'd like to get this out rather soon.

**Comment by eliaskousk** [comment]
@imphil I quickly saw the new PR changes and I like them. I'll see them again in more detail and notify you if I spot something.

As for the org changes I am a bit behind but will resume at the end of the week and will try to have stuff to show and discuss sometime next week. I agree we should take a closer look at those org actions and decide where to put them for easier access by the users.

**Comment by eliaskousk** [comment]
@imphil Please see my comments on #74

**Comment by eliaskousk** [comment]
It seems that I left this a bit (ok a lot!) behind on November. I'll try my best to have progress during the next couple of weeks - before our next meeting (around 27/12).

To accelerate the implementation and not redo work we should finalize the specs of what the organization actions are and what each one should do exactly. I'll prepare by the end of the week a short description of the current actions (the ones I proposed on October) so that we can spot problems and finalize them.

**Comment by imphil** [comment]
@eliaskousk what is the status here? Is there any specific question you have for me, or input I forgot about?

**Comment by eliaskousk** [comment]
@imphil Sorry for the delayed answer, I have pushed most of the functionality needed for organizations. You can see it in my [organizations branch of my fork](https://github.com/eliaskousk/librecores-web/tree/organizations).

I followed your suggestion on making the organization actions (join, leave etc) part of the settings, they all now have a settings prefix. I also made sure most of the routes are "uniform" for projects and organizations. Take a look at the [routes](https://github.com/eliaskousk/librecores-web/blob/organizations/site/src/Librecores/ProjectRepoBundle/Resources/config/routing.yml) and tell me what you think of them.

Now for the implementation I believe most of the needed stuff is there. Testing was done only manually but one can now:

- create an org
- remove an org
- view an org and it's projects, owner, members, join requests, etc.
- add a project under an org (at last!!!)
- edit a project under an org
- join an org that his not already a member and not the owner
- owner (only) can approve or deny a request to join the org
- view orgs that a member belongs or he requested to join (pending approval)

Templates are still f-ugly as hell but this is the stuff that the front-end designer will take care :)

Please tell me if you prefer me to make a PR now or check the stuff through my fork first. I prefer to make the PR after I do more testing and clean up some stuff though. Hopefully by the end of the week.

PS: During the last hour I had some trouble with the repo creation, it seems the rabbit mq pipeline is stuck. Just before everything was working fine, I don't know if its something I broke or a bug. I'll clean everything and let you know if it persists.

**Comment by eliaskousk** [comment]
Please use the new [org.polish](https://github.com/eliaskousk/librecores-web/tree/org.polish) branch on my fork, which contains the latest master changes, if you want to check out the work.

**Comment by imphil** [comment]
Thanks Elias for the great work. I've had a look at it and it looks like we're almost there, but fully reviewing would be easier in a PR. So please open one if you're ready for it.

At first glance, a couple things I saw:

- It would be great if we support multiple "owners" of an organization. The reason is that with organizations we can avoid "dead maintainer" issues, i.e. if one person is not available any more, nobody can take care of the organization and associated projects any more. While multiple owners are not required for a first version, we can maybe make the Entity/DB Model flexible enough to add this later without large database changes. So instead of having owner and members[name, name2, ...], maybe we can have members[{name, status = {OWNER, MEMBER}}, ...]

- Since we currently don't support deleting an org with associated projects (for that, projects would need to be transferred first, or deleted as well), we should just play safe and bail out in OrganizationController::requestsAction() with an error, instead of just putting a TODO there. Implementing the whole "correct" functionality can be done later.

- OrganizationController::searchAction() is probably unnecessary, the search functionality will be part of the search page.

- Nit: for if/foreach, etc., put the "{" on the same line as the if statement to make the code consistent.

**Comment by imphil** [comment]
On the frontend: I had a look at it and it's actually not much, I can take care of that. It will be faster for me than spec'ing out what we exactly want and handing that out to externals.

**Comment by wallento** [comment]
Sounds good, we can fast iterate over that I suppose, thanks to you both!

**Comment by eliaskousk** [comment]
I agree with the multiple owners and I'm currently looking at it. The easiest way to add this is to find a way to add / describe an extra column into the many-to-many join table that doctrine generates. If we can't do this we can extract this join table into a separate entity that we fully control. I also agree that we should definitely do such db change now instead of later and possibly leave the controller details for later. I will make the PR as soon as I integrate this change.

I also removed the search action, renamed the remove org controller into a delete org one and created a missing remove member from org controller that we need for cases were the owner (or one of them) wants to force the removal of a member from the organization.

I suppose we don't want to support one owner forcing the removal of other owners though, correct? Or should only the original owner (that I will call creator in the code-base) have this privilege?

Lastly sorry about the code formatting inconsistency but I'm in a phase of transition on placing the brace on the same-line on all my C/C++/PHP code and I keep using the old style. I think I've finally made peace with that though, since almost everyone is using this style and it's easier to just follow it instead of fighting it, it troubled me for over 10 years! I did some corrections on the latest commits and will keep it in mind for the future.

Latest changes are in the [org branch](https://github.com/eliaskousk/librecores-web/tree/org). I have deleted the other branches.

**Comment by imphil** [comment]
> I suppose we don't want to support one owner forcing the removal of other owners though, correct? Or should only the original owner (that I will call creator in the code-base) have this privilege?

In GitHub and GitLab it's possible AFAIK for one owner to remove the other owners, and I think that's sensible and makes our concept easier to understand. Otherwise we'd have three roles, creator, owner and member. I think owner and member are sufficient, and the one-off case of someone fighting with someone else over ownership rights and deleting stuff can be handled by replaying a backup if this really sould become necessary at some point in time.

> Lastly sorry about the code formatting inconsistency but I'm in a phase of transition on placing the brace on the same-line on all my C/C++/PHP code and I keep using the old style.

no worries, that's not blocking anything.

**Comment by eliaskousk** [comment]
I have completed the required additions to support multiple owners. It took a lot of changes but the solution I think is now cleaner and better. You can see the changes in the [organizations branch](https://github.com/eliaskousk/librecores-web/tree/organizations) and I'm ready to do a PR sometime during the weekend so that we can start reviewing it. I just need to explain in a short text on the PR what we are ready to support with these changes so that other members have a clear picture and do a better review job.

**Comment by imphil** [comment]
Great! If you find time to open the PR I can have a look at it on Sunday. Thanks already now!

**Comment by eliaskousk** [comment]
Submitted the PR (#101), please be gentle on your review! :)

**Comment by imphil** [comment]
Let's close this for now that the functionality is there, and continue in independent issues for the style and other follow-ups. Thanks Elias for the implementation!
