### ISSUE TITLE
user profile page: projects should probably be links

### ISSUE THREAD

**Issue by cliffordwolf** [librecores/librecores-web#72]
A user profile page (such as https://www.librecores.org/p/cliffordwolf) lists the projects for this user. However, the projects are not links. I guess they should be links to the respective project pages.

Also: The "Projects" `<h2>` header looks a bit awkward imo. Simply removing the element improves imo the look of the page drastically. (But this is just a personal style preference, of course. Feel free to ignore, I just wanted to mention it as I'm already writing this issue.. ;)

**Comment by imphil** [comment]
Thanks for reporting this, and I'm *very* sorry for not getting back to you earlier about this. I just didn't have time  until now that LibreCores development has picked up some speed again. This is now fixed in master and will be part of the next deployment push (about to happen before the weekend, so stay tuned!)
