### ISSUE TITLE
Create new user account on LibreCores

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#8]
Currently supported:
- GitHub login
- Google login
- site login

Test at http://stage.librecores.org/register/

**Comment by eliaskousk** [comment]
Hello,

what is the current status of the project? I want to help, initially with testing anything developed thus far, bug issues etc and later on with actual development of features since I have experience with Symfony. I will have limited time on May / June since I'm preparing / will start working for one of FOSSi' GSoC projects, but I love Symfony and hopefully I will be able to find some time to also help here. Should I talk about this with Stefan, Philip or Olof (my GSoC mentor) on IRC (my nick is eliask)?

Best,
Elias

P.S I registered an account on the staging area.

**Comment by imphil** [comment]
Hi Elias,

great that you want to joint the effort! All code that's available today is pushed, for testing it's best to get a vagrant development environment with the latest code up and running. I'm the main contact person, so let me know if you find anything. If you have time to take on any of the open issues, that's great as well! It's probably easiest to coordinate with me first quickly to make sure we don't duplicate work. I'm usually not on IRC, but you can reach me by mail any time.

Philipp

**Comment by olofk** [comment]
Not sure what's different from this and #9, but creating an account (via github) and login/logout works fine
