### ISSUE TITLE
Show project activity metrics

### ISSUE THREAD

**Issue by asb** [librecores/librecores-web#80]
I thought the Visual Studio Code plugin index had a [nice idea](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim). For projects on GitHub, list activity metrics, e.g.:
9 Pull Requests
97 Open Issues
Last commit: 4 days ago

**Comment by oleg-nenashev** [comment]
It would be very useful. The only problem is that polling much things from GitHub may finally lead to the violation of the REST API limit. I see two possible ways:
* Cache the data in LibreCores and update on the daily basis
* Just let Web Browsers retrieve the data on their own (requires some JavaScript coding)

On the other hand, it can be easily done just by embedding GitHub shields (also safe for API calls limit IIRC). Here is a good list of available Shields (including GitHub ones): http://shields.io/

**Comment by asb** [comment]
And you could just have a server-side process retrieve the .svg from shields.io and extract the text for formatting in your preferred form. REST API problem solved, right? :)

**Comment by asb** [comment]
Actually they support .json output too (https://img.shields.io/github/issues-closed/badges/shields.json).

**Comment by berndca** [comment]
The [github REST API rate limit for authenticated requests](https://developer.github.com/v3/#rate-limiting) is 5000 requests per hour. 

I had no problems using the API to extract repo info about  [open source HDL repos](https://berndca.github.io/discover_fossi/).  @oleg-nenashev  Is there a specific issue you are referring to?

I would create an AWS lamdba CRON job to extract all required info to a single json file perhaps once a day which I don't think qualifies for **aggressive polling**. I'd be happy to help setting things up.

**Comment by oleg-nenashev** [comment]
@berndca 

> I had no problems using the API to extract repo info about open source HDL repos. @oleg-nenashev Is there a specific issue you are referring to?

Well, we have issues with the GitHub API limit for authenticated users. E.g. in Jenkins project there were a couple of recent Infra issues due to it.

**Comment by oleg-nenashev** [comment]
Created #83

**Comment by eliaskousk** [comment]
Updated #83

**Comment by eliaskousk** [comment]
We can also use the [Github API client library](https://github.com/KnpLabs/php-github-api) which seems great for our purposes and should be very easy to use inside our project.***

Please see their [doc](https://github.com/KnpLabs/php-github-api/tree/1.7/doc) folder for a lot of examples on various data that we could get from each hosted project. We can identify a set of things that are useful for LibreCores and fetch them using this library.

@oleg-nenashev @berndca  You raised some concerns about the API's consumption limit. Since I haven't used it before, do these limits only apply for authenticated users? We shouldn't need to be authenticated right? We only fetch data for other user's repos, not data for our own account which is the reason to get authenticated. Is there something I miss here?

*** It uses the [HTTPlug](http://httplug.io) HTTP client abstraction library underneath which follows [PSR-7](http://www.php-fig.org/psr/psr-7/). This is really cool and I at last have reason to use it :-P

**Comment by imphil** [comment]
I'm currently rather busy, but just a quick drive-by until I have time to look closer: the design goal was to stay as much as we can with data we can get from a git repo itself, since we want to support other hosting sites than github as well. This was mentioned a requirement from very early on, due to the fact that it seems some valuable people in the HW community want to use their own hosting.

In order to avoid duplication of work for each git hosting provider and using their APIs, we fetch the repo and get the statistics from there. That's what the UpdateProject cron job does currently.

If we want to special-case some github things, that's fine with me (such as # of open issues, etc.). But we should not rely too much on the GH API for things that are already inside the repo itself (such as contributors, commit stats, etc.).

**Comment by eliaskousk** [comment]
@imphil I agree and this I think is still our design goal. Maybe identifying things that are common to all hosting providers (most of what we already have) and have separate sections applicable to each different provider. What we discuss here is actually the Github section of the project view of LibreCores.

**Comment by berndca** [comment]
Thats very interesting. Do you have the code for the UpdateProject cron job in your github repo? Is it just running 

```git pull origin master```

If you have access to the actual repo you can extract key stats from the repo meta data.

The only downside is that I’m not sure how well this scales and of course this is not something you want to run on your production web server.

A far more scalable approach would be based on git hooks. The problem with git hooks is that you need the user to cooperate and install the hooks. But this would eliminate a lot of pulling.

IMO the extraction of repository stats should be implemented either as git hook using AWS API Gateway and AWS lambda or polling through AWS lambda cron jobs. Unlike the overpriced and underpowered AWS EC2 instances, AWS lambda comes with a huge number of free minutes and it helps reducing the load  and avoiding load spikes of your production server.

@eliaskousk  I would be very cautious with adding support for various git providers and issue trackers in your web application. Perhaps it makes sense to take a step back and think about the database schema for the models you would like to use and push the functionality of mapping to specific providers into external scripts with a well defined interface like JSON or XML (with schemas).

**Comment by Agathver** [comment]
@oleg-nenashev Should I assign this one to myself ?
