### ISSUE TITLE
Markdown Parser: Synchronize with GH

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#86]
Our MarkDown parser seems to be slightly different than the GitHub one.

See this project:
https://github.com/kactus2/kactus2dev/blob/master/README.md
https://www.librecores.org/epekkar/kactus2

**Comment by imphil** [comment]
I guess we'll never be able to get bug-free output unless we go with the exact same solution as GH uses (https://github.com/github/markup). 

Idea:
- Switch the Project::descriptionText and Project::licenseText fields to contain processed HTML.
- wrap that Ruby stuff in a separate script that we call when processing.
- Switch from editing MarkDown to HTML on LibreCores itself.

**Comment by olofk** [comment]
As you say, we will never have bug-free output unless using the same solution as github. The problem is that this isn't enough, as the text might contain internal links that will be broken. The source could also be asciidoc or Restructured Text. (For the latter, I have a similar problem with the README.rst in FuseSoC that is also used by pypi, and has broken links there). Wouldn't the easiest solution be to do a dumb import, but give users the chance to edit and fix-up things. I think it will be a lot of effort spent in vain, trying to emulate other parsers, and editing the raw md/adoc/rst is IMO much nicer than preprocessed html

**Comment by berndca** [comment]
The a HTML version rendered by GitHub's Markup can be obtained through the AGitHub API see #116 for an example.

@olofk Just change all your links to full URL's and they will work everywhere. For instance replace
```doc/fusesoc.adoc``` with ```https://github.com/olofk/fusesoc/blob/master/doc/fusesoc.adoc```

**Comment by imphil** [comment]
done in PR #123

**Comment by imphil** [comment]
For example https://www.librecores.org/epekkar/kactus2 shows up correctly now.
